### ISSUE TITLE
Support go 1.7

### ISSUE THREAD

**Issue by ThreeFx** [resulknad/networks2tester#1]
I currently can't run this with go 1.7 installed (Debian stable).

**Comment by resulknad** [comment]
Will look into it, a possible quick fix would be compiling it in a container: https://hub.docker.com/_/golang/
I might just add the binary, would probably be good enough for most people...

**Comment by ThreeFx** [comment]
That'd be really helpful, thanks!

**Comment by ThreeFx** [comment]
Closing this as you helpfully provide a binary. Thanks!
